Add lunarclient binary path on linux (/usr/bin) and improve chrome_debugger.rs.
Nilsen84/lunar_launcher_inject pull request #1
Opened 2022-10-23 20:49 UTC by Monmcgt

### Lunarclient binary path 
`/usr/bin/lunarclient`

### Improve chrome_debugger.rs
By retrying connecting to the remote debugging target if the previous attempt failed. (max 10 tries)

2022-10-23 21:12 UTC, Zxnii approved these changes

2022-10-23 22:18 UTC, Nilsen84 requested changes
Looks great! On top of the changes I've proposed I'd recommend lowering the max retries to something like 3 since it's realistically never gonna take node more than 3 seconds to start the debugging server.

2022-10-23 22:18 UTC, Nilsen84 commented on src/chrome_debugger.rs
> +                panic!("Failed to get targets");
```suggestion
                bail!("Failed to get targets");
```

2022-10-23 22:18 UTC, Nilsen84 commented on src/chrome_debugger.rs
> +        while targets.len() == 0 {
```suggestion
        while targets.is_empty() {
```

2022-10-23 22:18 UTC, Nilsen84 commented on src/chrome_debugger.rs
>          let selected = targets.first().context("no debugging targets found")?;
it's safe to use unwrap here since we know the targets Vec won't be empty
```suggestion
        let selected = targets.first().unwrap();
```

2022-10-23 22:18 UTC, Nilsen84 commented on src/chrome_debugger.rs
> +                format!("http://localhost:{port}/json/list", port = port)
```suggestion
                format!("http://localhost:{}/json/list", port)
```

2022-10-24 06:52 UTC, Monmcgt commented
Fixed!

2022-10-24 07:01 UTC, Monmcgt commented
Fixed!

2022-10-24 20:07 UTC, Nilsen84 approved these changes

2022-10-24 20:08 UTC, merged